### PR TITLE
Widen type of ValidationResult to allow array params

### PR DESCRIPTION
**Pull request by laurieboyes**
Fixes https://github.com/fastify/fastify-error/issues/3

Can’t work out if using `as` in the [tsd](https://www.npmjs.com/package/tsd) tests is cheating 😄  Will defer to you.

### CODE REVIEW

**Comment by mcollina** [comment]
cc @Ethan-Arrowood

**Comment by Ethan-Arrowood** [comment]
Yeah this really isn't testing anything 😅 You'll need to pass a variable defined as a Record to that assertion

**Comment by Ethan-Arrowood** [comment]
This should pass without the `as` cast

**Comment by laurieboyes** [comment]
Ah yes I see, cheers Ethan 👍

**Comment by laurieboyes** [comment]
Ace 👍 would one of you mind pressing the merge button?

**Pull request merged**
