### PR TITLE
Remove ts-standard

### PR DESCRIPTION
**Pull request by trim21**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

`standard` doesn't work will for typescript, use eslint with `eslint-config-standard-with-typescript` directly

### CODE REVIEW

**Comment by jsumners** [comment]
> `standard` doesn't work will for typescript

In what way?

**Comment by trim21** [comment]
> > `standard` doesn't work will for typescript
> 
> In what way?

it only check js files be default and can't parse ts files.

**Comment by trim21** [comment]
> From what I can see in the docs https://www.npmjs.com/package/ts-standard, it just requires some configuration to target the appropriate files. But I know nothing outside of that.

https://github.com/fastify/fastify-error/pull/101#issuecomment-1538079489

**Comment by Fdawgs** [comment]
superceded by #104

**Pull request closed without merging**
