### PR TITLE
pref:  use new.target to replace instanceof

### PR DESCRIPTION
**Pull request by xtx1130**
as titled

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
how much does this improve things?

**Comment by mcollina** [comment]
For the record:

```js
const max = 100000000

function InstanceOfClass () {
  if (!(this instanceof InstanceOfClass)) {
    return new InstanceOfClass()
  }
}

function NewTargetClass () {
  if (!new.target) {
    return new NewTargetClass()
  }
}

console.time('InstanceOfClass')
for (let i = 0; i < max; i++) {
  InstanceOfClass()
}
console.timeEnd('InstanceOfClass')

console.time('NewTargetClass')
for (let i = 0; i < max; i++) {
  NewTargetClass()
}
console.timeEnd('NewTargetClass')
```

results in:

```
InstanceOfClass: 3.741s
NewTargetClass: 1.154s
```

Impressive, I didn't know about this!

**Comment by xtx1130** [comment]
image

The result is almost the same between `=== undefined`  and   `!`

**Comment by xtx1130** [comment]
I just saw the mentioned above. It is really faster.
```js
const max = 100000000

function InstanceOfClass () {
  if (!(this instanceof InstanceOfClass)) {
    return new InstanceOfClass()
  }
}

function NewTargetClass () {
  if (!new.target) {
    return new NewTargetClass()
  }
}

function NewTargetClassUndefined () {
  if (new.target === undefined) {
    return new NewTargetClass()
  }
}

console.time('NewTargetClass')
for (let i = 0; i < max; i++) {
  NewTargetClass()
}
console.timeEnd('NewTargetClass')

console.time('InstanceOfClass')
for (let i = 0; i < max; i++) {
  InstanceOfClass()
}
console.timeEnd('InstanceOfClass')

console.time('NewTargetClassWithUndefined')
for (let i = 0; i < max; i++) {
  NewTargetClassUndefined()
}
console.timeEnd('NewTargetClassWithUndefined')
```

The result is :

```bash
NewTargetClass: 1.169s
InstanceOfClass: 3.983s
NewTargetClassWithUndefined: 52.08ms
```

`=== undefined`  is more faster at nodejs v16, @kurtextrem would you mind to send a PR to update this?

**Comment by kurtextrem** [comment]
At this point we probably shouldn't care or not put any further time into this, see https://github.com/fastify/fastify-error/pull/61

**Pull request merged**
