### PR TITLE
types: check error argument type

### PR DESCRIPTION
**Pull request by trim21**
#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

```ts
const CustomTypedArgError = createError<[string]>('OTHER_CODE', 'expect %s message', 400)

CustomTypedArgError('a')
// @ts-expect-error
CustomTypedArgError('a', 'b')
// @ts-expect-error
new CustomTypedArgError('a', 'b')
// @ts-expect-error
CustomTypedArgError(1)
// @ts-expect-error
new CustomTypedArgError(1)
```

### CODE REVIEW

**Comment by trim21** [comment]
some minor space change.

**Review by Fdawgs — CHANGES_REQUESTED** [review]
Please revert prettier style changes, this repo uses Standard.

**Comment by trim21** [comment]
Yes but it pass `npm run lint`

**Comment by trim21** [comment]
Oh i see, standard is broken in TypeScript, ts files are not checked.

**Comment by Uzlopak** [comment]
Also please use expectError of tsd, instead of ts-expect-error declarations

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Fdawgs — APPROVED** [review]

**Comment by trim21** [comment]
any plan on merging this?

**Comment by Uzlopak** [comment]
Can you extend the typings tests to this, please?

```typescript
const CustomTypedArgError = createError<[string]>('OTHER_CODE', 'expect %s message', 400)
CustomTypedArgError('a')
new CustomTypedArgError('a')
expectError(CustomTypedArgError('a', 'b'))
expectError(new CustomTypedArgError('a', 'b'))
expectError(CustomTypedArgError(1))
expectError(new CustomTypedArgError(1))

const CustomTypedArgError2 = createError<string, number, [string]>('OTHER_CODE', 'expect %s message', 400)
CustomTypedArgError2('a')
new CustomTypedArgError2('a')
expectError(CustomTypedArgError2('a', 'b'))
expectError(new CustomTypedArgError2('a', 'b'))
expectError(CustomTypedArgError2(1))
expectError(new CustomTypedArgError2(1))

const CustomTypedArgError3 = createError<string, number, [string, string]>('OTHER_CODE', 'expect %s message but got %s', 400)
expectError(CustomTypedArgError3('a'))
CustomTypedArgError3('a', 'b')
new CustomTypedArgError3('a', 'b')
expectError(CustomTypedArgError3(1))
expectError(new CustomTypedArgError3(1))
expectError(new CustomTypedArgError3(1,2))
expectError(new CustomTypedArgError3('1',2))
expectError(new CustomTypedArgError3(1,'2'))

const CustomTypedArgError4 = createError<string, number, [string, string]>('OTHER_CODE', 'expect %s message but got %s', 400)
expectError(CustomTypedArgError4('a'))
CustomTypedArgError4('a', 'b')
new CustomTypedArgError4('a', 'b')
expectError(CustomTypedArgError4(1))
expectError(new CustomTypedArgError4(1))
expectError(new CustomTypedArgError4(1,2))
expectError(new CustomTypedArgError4('1',2))
expectError(new CustomTypedArgError4(1,'2'))


const CustomTypedArgError5 = createError<[string, string, string, string]>('OTHER_CODE', 'expect %s message but got %s. Please contact %s by emailing to %s', 400)
expectError(CustomTypedArgError5('a'))
expectError(new CustomTypedArgError5('a', 'b'))
expectError(new CustomTypedArgError5('a', 'b', 'c'))
CustomTypedArgError5('a', 'b', 'c', 'd')
expectError(new CustomTypedArgError5('a', 'b', 'c', 'd', 'e'))

const CustomTypedArgError6 = createError<string, number, [string, string, string, string]>('OTHER_CODE', 'expect %s message but got %s. Please contact %s by emailing to %s', 400)
expectError(CustomTypedArgError6('a'))
expectError(new CustomTypedArgError6('a', 'b'))
expectError(new CustomTypedArgError6('a', 'b', 'c'))
CustomTypedArgError6('a', 'b', 'c', 'd')
expectError(new CustomTypedArgError6('a', 'b', 'c', 'd', 'e'))

```

**Review by Uzlopak — CHANGES_REQUESTED** [review]
The functionality is given, but to check if everything is correct, I needed to modify the typings test. I would like to get that added to this PR. I would than merge it.

**Review by Uzlopak — APPROVED** [review]
LGTM

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by Uzlopak** [comment]
I didnt forget you ;). I tried to merge it about 10 times when github had issues.

**Comment by trim21** [comment]
New release for this?

**Comment by Uzlopak** [comment]
Well this is some job for @mcollina , @eomm and so.

**Pull request merged**
