### PR TITLE
Adds validationContext to FastifyError type

### PR DESCRIPTION
**Pull request by ksmithut**
Per the various examples on [these docs](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md), validationContext is often used to determine different error messages, especially when trying to inform the client which part of the input failed validation. This PR adds the validationContext property to the FastifyError

We could probably give the validationContext a union type with `'body' | 'params' | 'querystring' | 'headers'`. Thoughts?

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
I don't think we manage that property here. `validationContext` come from Ajv.

**Comment by mcollina** [comment]
@Ethan-Arrowood wdyt?

**Comment by ksmithut** [comment]
This is the code I'm currently working with:

```js
fastify.setErrorHandler((error, request, reply) => {
    const { validation, validationContext } = error
    if (validation) {
      return reply.status(400).send({
        code: 'INVALID_PARAMS',
        details: { context: validationContext, errors: validation }
      })
    }
    request.log.error({ err: error })
    reply.status(500)
    reply.send({ code: 'INTERNAL_SERVER_ERROR' })
  })
```

I'm getting a typescript error `Property 'validationContext' does not exist on type 'FastifyError'`. Following type definitions led me to here, but if it makes more sense to extend the type in fastify itself, I could get behind that.

**Comment by Ethan-Arrowood** [comment]
hmm so since ajv is only on `fastify`. We probably need to add it over there instead.

**Comment by ksmithut** [comment]
I did a search for `validationContext` across ajv but didn't find any mention of it. It's in fastify though, so I could still see fastify extending the type of the class exposed here

**Comment by mcollina** [comment]
I'm closing this one. One of the types of error that is forwarded to the errorHandler are validation errors. Those will have that property.

**Comment by ksmithut** [comment]
K sounds good. But doesn't this error class expose validation errors specific to AJV? Sounds like we should remove that from this package as well if validation errors don't belong here

**Comment by mcollina** [comment]
>  But doesn't this error class expose validation errors specific to AJV? 

Where did you find it? There is _nothing_ AJV specific in https://github.com/fastify/fastify-error/blob/master/index.js.

**Comment by mcollina** [comment]
I see where the confusion come from: https://github.com/fastify/fastify-error/blob/9166733cf44b59b83e02f35a2d5c13cf4292aad9/index.d.ts#L4-L13. All of that can be removed, yes. It's not part of this module.

**Comment by ksmithut** [comment]
Cool, sounds good. I'll go ahead and close this then.

**Comment by Ethan-Arrowood** [comment]
Yeah anything validation related (types included should be removed here. The main fastify repo should depend on these types and extend them to include things like validation results

**Pull request closed without merging**
