### PR TITLE
chore: missing TS peer deps

### PR DESCRIPTION
**Pull request by trim21**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by climba03003** [comment]
Thanks for the PR.

`tsd` use it's own version of `typescript`.
We have no command or code directly link to use `typescript` either.
So, closing.

**Comment by trim21** [comment]
> Thanks for the PR.
> 
> `tsd` use it's own version of `typescript`. We have no command or code directly link to use `typescript` either. So, closing.

ts-standard require eslint ts parser and have a peer deps of ts

**Comment by trim21** [comment]
it's not for tsd

**Comment by climba03003** [comment]
Absolutely a disaster when choosing to use `ts-standard`.

**Comment by trim21** [comment]
Yes, another option

```json
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.59.2",
    "@typescript-eslint/parser": "^5.0.0",
    "benchmark": "^2.1.4",
    "eslint": "^8.40.0",
    "eslint-config-standard-with-typescript": "^34.0.1",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-n": "^15.0.0",
    "eslint-plugin-promise": "^6.0.0",
    "tap": "^16.0.0",
    "tsd": "^0.28.0",
    "typescript": "^5.0.4"
  },
```

**Comment by Uzlopak** [comment]
I for the same reasons dislike this PR.

**Pull request closed without merging**
